apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-prometheus-config
  namespace: default
data:
  30-prometheus.conf: |
    prometheus.return_per_object_metrics = true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: rabbitmq-inst
  name: rabbitmq-inst
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - image: rabbitmq:3.11.15
        name: rabbitmq-inst
        ports:
        - containerPort: 4369
        - containerPort: 5671
        - containerPort: 5672
        - containerPort: 15691
        - containerPort: 15692
        - containerPort: 25672
        volumeMounts:
        - name: rabbitmq-prometheus-config-volume
          mountPath: /etc/rabbitmq/conf.d/30-prometheus.conf
          readOnly: true
          subPath: 30-prometheus.conf
      volumes:
      - name: rabbitmq-prometheus-config-volume
        configMap:
          name: rabbitmq-prometheus-config

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  labels: 
    operated-prometheus: "true"
spec:
  selector:
    app: rabbitmq
  ports:
    - protocol: TCP
      port: 5672
      name: conn
    - protocol: TCP
      port: 15692
      name: metric
